test("Hello World", () => {});

test("Failure test", () => {
	throw new Error("Failure");
});
